#10 UML
kasmar00/IO-Projekt pull request #22
Opened 2021-12-20 17:35 UTC by Jurasikov

2021-12-21 18:30 UTC, AnnaPralat requested changes
zamień proszę CapitalizeText na UpperText lub LowerText

CapitalizeText (zamienione na Upper lub Lower), ToShortcut i InverseText nie powinny mieć połączenia z Text (patrz wzorzec projektowy Dekorator)

nie jestem przekonana co do połączeń między TextTransformerService, a TextImpl i Text

2021-12-21 21:01 UTC, AnnaPralat reviewed
po stronie dekoratorów na pewno okej, a co do reszty to jeszcze prośba o zerknięcie @kasmar00 i @PatrykHub

2021-12-21 22:21 UTC, kasmar00 approved these changes

2021-12-21 22:25 UTC, merged

2021-12-22 08:50 UTC, kasmar00 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Zrobić UML](https://trello.com/c/e436XiZF/38-zrobi%C4%87-uml)